### ISSUE TITLE
How to get the  password for the zip file ‘11kHands_gender_afifi2017’ ？

### ISSUE THREAD

**Issue by Yimin-Yuan** [mahmoudnafifi/11K-Hands#1]

**Comment by mahmoudnafifi** [comment]
There is no need for password now. You can download the source code here from Github or from the following links:
Gender classification: https://drive.google.com/file/d/1dOIRGMsNPcash6_1mjsOco981AI0PuGX/view
Biometric identification: https://drive.google.com/file/d/1Fmk1KCbIzSfQVGsISwFUwhp2HykGE43R/view

**Comment by Yimin-Yuan** [comment]
Thanks a lot!


I have another question that which is the file‘o_p_1.mat’ in biometric_identification\get_all_features.m line20? Is it the trained SVM or CNN? Thank you very much!


------------------


 




------------------ 原始邮件 ------------------
发件人: "Mahmoud Afifi"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 上午9:01
收件人: "mahmoudnafifi/11K-Hands"<11K-Hands@noreply.github.com>;
抄送: "yym"<420729854@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mahmoudnafifi/11K-Hands] How to get the  password for the zip file ‘11kHands_gender_afifi2017’ ？ (#1)




There is no need for password now. You can download the source code here from Github or from the following links:
 Gender classification: https://drive.google.com/file/d/1dOIRGMsNPcash6_1mjsOco981AI0PuGX/view
 Biometric identification: https://drive.google.com/file/d/1Fmk1KCbIzSfQVGsISwFUwhp2HykGE43R/view

**Comment by mahmoudnafifi** [comment]
For biometric identification, we relied only on SVM models that take deep features of the trained model for gneder classification. The model you referred for is the CNN trained model for gender classification. We used it to extract the deep features, then we feed them to the SVM model.

**Comment by Yimin-Yuan** [comment]
Thanks a lot!


------------------


 




------------------ 原始邮件 ------------------
发件人: "Mahmoud Afifi"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 凌晨5:57
收件人: "mahmoudnafifi/11K-Hands"<11K-Hands@noreply.github.com>;
抄送: "yym"<420729854@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mahmoudnafifi/11K-Hands] How to get the  password for the zip file ‘11kHands_gender_afifi2017’ ？ (#1)




For biometric identification, we relied only on SVM model that takes deep features of the trained model for gneder classification. The model you referred for is the trained model for gender classification. We used it to extract the deep features, then we feed them to the SVM model.
